shamefullyHoist: true
strictPeerDependencies: false
ignoreWorkspaceRootCheck: true
useNodeVersion: 22.17.0

overrides:
  '@eslint-community/eslint-utils': ^4.9.0
  '@typescript-eslint/types': ^8.50.1
  '@typescript-eslint/utils': ^8.50.1
  eslint: ^9.39.2
  tsx: ^4.21.6
catalog:
  '@antfu/install-pkg': ^1.1.0
  '@antfu/ni': ^28.0.0
  '@clack/prompts': ^0.11.0
  '@eslint-community/eslint-plugin-eslint-comments': ^4.5.0
  '@eslint-react/eslint-plugin': ^2.3.12
  '@eslint/config-inspector': ^1.4.2
  '@eslint/markdown': ^7.5.1
  '@next/eslint-plugin-next': ^16.1.1
  '@prettier/plugin-xml': ^3.4.2
  '@stylistic/eslint-plugin': ^5.6.1
  '@types/eslint-plugin-jsx-a11y': ^6.10.1
  '@types/node': ^24.10.2
  '@types/yargs': ^17.0.35
  '@typescript-eslint/eslint-plugin': ^8.50.1
  '@typescript-eslint/parser': ^8.50.1
  eslint-plugin-erasable-syntax-only: ^0.4.0
  '@unocss/eslint-plugin': ^66.5.10
  '@vinicunca/perkakas': ^1.9.0
  '@vitest/eslint-plugin': ^1.5.2
  astro-eslint-parser: ^1.2.2
  bumpp: ^10.3.2
  bundle-require: ^5.1.0
  eslint: ^9.39.2
  eslint-config-flat-gitignore: ^2.1.0
  eslint-flat-config-utils: ^2.1.4
  eslint-merge-processors: ^2.0.0
  eslint-plugin-antfu: ^3.1.1
  eslint-plugin-astro: ^1.5.0
  eslint-plugin-command: ^3.3.1
  eslint-plugin-format: ^1.1.0
  eslint-plugin-import-lite: ^0.3.0
  eslint-plugin-jsdoc: ^61.5.0
  eslint-plugin-jsonc: ^2.21.0
  eslint-plugin-jsx-a11y: ^6.10.2
  eslint-plugin-n: ^17.23.1
  eslint-plugin-no-only-tests: ^3.3.0
  eslint-plugin-perfectionist: ^4.15.1
  eslint-plugin-pnpm: ^1.4.2
  eslint-plugin-react-hooks: ^7.0.1
  eslint-plugin-react-refresh: ^0.4.24
  eslint-plugin-regexp: ^2.10.0
  eslint-plugin-solid: ^0.14.5
  eslint-plugin-sonarjs: ^3.0.5
  eslint-plugin-svelte: ^3.13.1
  eslint-plugin-toml: ^0.12.0
  eslint-plugin-unicorn: ^62.0.0
  eslint-plugin-unused-imports: ^4.3.0
  eslint-plugin-vue: ^10.6.2
  eslint-plugin-vuejs-accessibility: ^2.4.1
  eslint-plugin-yml: ^1.19.0
  eslint-processor-vue-blocks: ^2.0.0
  eslint-typegen: ^2.3.0
  execa: ^9.6.1
  globals: ^16.5.0
  is-ci: ^4.1.0
  jiti: ^2.6.1
  jsonc-eslint-parser: ^2.4.2
  lint-staged: ^16.2.7
  local-pkg: ^1.1.2
  prettier-plugin-astro: ^0.14.1
  prettier-plugin-slidev: ^1.0.5
  react: ^19.2.1
  simple-git-hooks: ^2.13.1
  svelte: ^5.46.0
  svelte-eslint-parser: ^1.4.1
  taze: ^19.9.2
  tinyglobby: ^0.2.15
  toml-eslint-parser: ^0.10.1
  tsdown: ^0.18.2
  tsx: ^4.21.0
  typescript: ^5.9.3
  vitest: ^4.0.16
  vue: ^3.5.26
  vue-eslint-parser: ^10.2.0
  yaml-eslint-parser: ^1.3.2
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
  - unrs-resolver
