packages:
  - eslint
  - docs
overrides:
  '@eslint-community/eslint-utils': ^4.4.1
  '@typescript-eslint/utils': ^8.26.0
  eslint: ^9.22.0
  tsx: ^4.19.3
catalog:
  '@antfu/install-pkg': ^1.0.0
  '@antfu/ni': ^23.3.1
  '@clack/prompts': ^0.10.0
  '@eslint-community/eslint-plugin-eslint-comments': ^4.4.1
  '@eslint-react/eslint-plugin': ^1.31.0
  '@eslint/config-inspector': ^1.0.2
  '@eslint/markdown': ^6.3.0
  '@iconify/json': ^2.2.314
  '@prettier/plugin-xml': ^3.4.1
  '@stylistic/eslint-plugin': ^4.2.0
  '@stylistic/eslint-plugin-migrate': ^4.2.0
  '@types/node': ^22.13.10
  '@types/yargs': ^17.0.33
  '@typescript-eslint/eslint-plugin': ^8.26.0
  '@typescript-eslint/parser': ^8.26.0
  '@unocss/eslint-plugin': ^66.0.0
  '@vinicunca/perkakas': ^1.3.0
  '@vinicunca/unocss-preset': ^1.8.0
  '@vitest/eslint-plugin': ^1.1.36
  astro-eslint-parser: ^1.2.1
  bumpp: ^10.0.3
  eslint: ^9.22.0
  eslint-config-flat-gitignore: ^2.1.0
  eslint-flat-config-utils: ^2.0.1
  eslint-merge-processors: ^2.0.0
  eslint-plugin-antfu: ^3.1.1
  eslint-plugin-astro: ^1.3.1
  eslint-plugin-command: ^3.1.0
  eslint-plugin-format: ^1.0.1
  eslint-plugin-import-x: ^4.6.1
  eslint-plugin-jsdoc: ^50.6.3
  eslint-plugin-jsonc: ^2.19.1
  eslint-plugin-n: ^17.16.2
  eslint-plugin-no-only-tests: ^3.3.0
  eslint-plugin-perfectionist: ^4.10.1
  eslint-plugin-pnpm: ^0.1.2
  eslint-plugin-react-hooks: ^5.2.0
  eslint-plugin-react-refresh: ^0.4.19
  eslint-plugin-regexp: ^2.7.0
  eslint-plugin-solid: ^0.14.5
  eslint-plugin-sonarjs: ^3.0.2
  eslint-plugin-svelte: ^3.1.0
  eslint-plugin-toml: ^0.12.0
  eslint-plugin-unicorn: ^57.0.0
  eslint-plugin-unused-imports: ^4.1.4
  eslint-plugin-vue: ^10.0.0
  eslint-plugin-yml: ^1.17.0
  eslint-processor-vue-blocks: ^2.0.0
  eslint-typegen: ^2.0.0
  execa: ^9.5.2
  fuse.js: ^7.1.0
  globals: ^16.0.0
  is-ci: ^4.1.0
  jiti: ^2.4.2
  jsonc-eslint-parser: ^2.4.0
  lint-staged: ^15.4.3
  local-pkg: ^1.1.1
  postcss-nested: ^7.0.2
  prettier-plugin-astro: ^0.14.1
  prettier-plugin-slidev: ^1.0.5
  radix-vue: ^1.9.17
  react: ^19.0.0
  simple-git-hooks: ^2.11.1
  svelte: ^5.22.6
  svelte-eslint-parser: ^1.0.1
  taze: ^18.7.1
  toml-eslint-parser: ^0.10.0
  tsup: ^8.4.0
  tsx: ^4.19.3
  typescript: ^5.8.2
  unocss: ^66.0.0
  unplugin-vue-components: ^28.4.1
  vitepress: ^1.6.3
  vitest: ^3.0.8
  vue: ^3.5.13
  vue-eslint-parser: ^10.1.1
  yaml-eslint-parser: ^1.3.0
onlyBuiltDependencies:
  - esbuild
