catalog:
  '@antfu/install-pkg': ^1.0.0
  '@clack/prompts': ^0.10.0
  '@eslint-community/eslint-plugin-eslint-comments': ^4.4.1
  '@eslint-react/eslint-plugin': ^1.26.2
  '@eslint/config-inspector': ^1.0.0
  '@eslint/markdown': ^6.2.2
  '@iconify/json': ^2.2.307
  '@prettier/plugin-xml': ^3.4.1
  '@stylistic/eslint-plugin': ^4.0.0-beta.1
  '@stylistic/eslint-plugin-migrate': ^4.0.0-beta.1
  '@types/fs-extra': ^11.0.4
  '@types/node': ^22.13.4
  '@types/prompts': ^2.4.9
  '@types/yargs': ^17.0.33
  '@typescript-eslint/eslint-plugin': ^8.24.0
  '@typescript-eslint/parser': ^8.24.0
  '@unocss/eslint-plugin': ^65.5.0
  '@vinicunca/perkakas': ^1.2.3
  '@vinicunca/unocss-preset': ^1.1.4
  '@vitest/eslint-plugin': ^1.1.31
  astro-eslint-parser: ^1.2.1
  bumpp: ^10.0.3
  eslint: ^9.20.1
  eslint-config-flat-gitignore: ^2.0.0
  eslint-flat-config-utils: ^2.0.1
  eslint-merge-processors: ^2.0.0
  eslint-plugin-antfu: ^3.1.0
  eslint-plugin-astro: ^1.3.1
  eslint-plugin-command: ^3.1.0
  eslint-plugin-format: ^1.0.1
  eslint-plugin-import-x: ^4.6.1
  eslint-plugin-jsdoc: ^50.6.3
  eslint-plugin-jsonc: ^2.19.1
  eslint-plugin-n: ^17.15.1
  eslint-plugin-no-only-tests: ^3.3.0
  eslint-plugin-perfectionist: ^4.9.0
  eslint-plugin-react-hooks: ^5.1.0
  eslint-plugin-react-refresh: ^0.4.19
  eslint-plugin-regexp: ^2.7.0
  eslint-plugin-solid: ^0.14.5
  eslint-plugin-sonarjs: ^3.0.2
  eslint-plugin-svelte: ^2.46.1
  eslint-plugin-toml: ^0.12.0
  eslint-plugin-unicorn: ^56.0.1
  eslint-plugin-unused-imports: ^4.1.4
  eslint-plugin-vue: ^9.32.0
  eslint-plugin-yml: ^1.16.0
  eslint-processor-vue-blocks: ^2.0.0
  eslint-typegen: ^1.0.0
  execa: ^9.5.2
  fast-glob: ^3.3.3
  fs-extra: ^11.3.0
  fuse.js: ^7.1.0
  globals: ^15.15.0
  is-ci: ^4.1.0
  jiti: ^2.4.2
  jsonc-eslint-parser: ^2.4.0
  lint-staged: ^15.4.3
  local-pkg: ^1.0.0
  postcss-nested: ^7.0.2
  prettier-plugin-astro: ^0.14.1
  prettier-plugin-slidev: ^1.0.5
  radix-vue: ^1.9.14
  react: ^19.0.0
  rimraf: ^6.0.1
  simple-git-hooks: ^2.11.1
  svelte: ^5.20.1
  svelte-eslint-parser: ^0.43.0
  taze: ^18.5.0
  toml-eslint-parser: ^0.10.0
  tsup: ^8.3.6
  tsx: ^4.19.2
  typescript: ^5.7.3
  unocss: ^65.5.0
  unplugin-vue-components: ^28.1.0
  vitepress: ^1.6.3
  vitest: ^3.0.5
  vue: ^3.5.13
  vue-eslint-parser: ^9.4.3
  yaml-eslint-parser: ^1.2.3
packages:
  - eslint
  - docs
