catalogMode: prefer
strictPeerDependencies: false
ignoreWorkspaceRootCheck: true
shamefullyHoist: true
shellEmulator: true

catalogs:
  dev:
    '@antfu/ni': ^28.2.0
    '@eslint/config-inspector': ^1.4.2
    '@types/eslint-plugin-jsx-a11y': ^6.10.1
    '@types/node': ^25.3.0
    '@vinicunca/perkakas': ^1.13.0
    bumpp: ^10.4.1
    chokidar: ^5.0.0
    eslint-typegen: ^2.3.1
    execa: ^9.6.1
    jiti: ^2.6.1
    lint-staged: ^16.2.7
    pnpm-workspace-yaml: ^1.5.0
    simple-git-hooks: ^2.13.1
    tinyglobby: ^0.2.15
    tsdown: ^0.18.4
    tsx: ^4.21.0
    typescript: ^5.9.3
    vitest: ^4.0.18
  inline:
    find-up-simple: ^1.0.1
  peer:
    '@eslint-community/eslint-utils': ^4.9.1
    '@eslint-react/eslint-plugin': ^2.13.0
    '@next/eslint-plugin-next': ^16.1.6
    '@prettier/plugin-xml': ^3.4.2
    '@typescript-eslint/types': ^8.56.1
    '@typescript-eslint/utils': ^8.56.1
    astro-eslint-parser: ^1.3.0
    eslint: ^10.0.2
    eslint-plugin-astro: ^1.6.0
    eslint-plugin-erasable-syntax-only: ^0.4.0
    eslint-plugin-jsx-a11y: ^6.10.2
    eslint-plugin-react-hooks: ^7.0.1
    eslint-plugin-react-refresh: ^0.5.2
    eslint-plugin-solid: ^0.14.5
    eslint-plugin-svelte: ^3.15.0
    eslint-plugin-vuejs-accessibility: ^2.5.0
    prettier-plugin-astro: ^0.14.1
    prettier-plugin-slidev: ^1.0.5
    svelte: ^5.53.3
    svelte-eslint-parser: ^1.5.0
    vue: ^3.5.29
  prod:
    '@antfu/install-pkg': ^1.1.0
    '@clack/prompts': ^1.0.1
    '@eslint-community/eslint-plugin-eslint-comments': ^4.6.0
    '@eslint/markdown': ^7.5.1
    '@stylistic/eslint-plugin': ^5.9.0
    '@typescript-eslint/eslint-plugin': ^8.56.1
    '@typescript-eslint/parser': ^8.56.1
    '@unocss/eslint-plugin': ^66.6.0
    '@vitest/eslint-plugin': ^1.6.9
    eslint-config-flat-gitignore: ^2.2.1
    eslint-flat-config-utils: ^3.0.1
    eslint-merge-processors: ^2.0.0
    eslint-plugin-antfu: ^3.2.2
    eslint-plugin-command: ^3.5.1
    eslint-plugin-format: ^2.0.0
    eslint-plugin-import-lite: ^0.5.2
    eslint-plugin-jsdoc: ^62.7.1
    eslint-plugin-jsonc: ^3.1.0
    eslint-plugin-n: ^17.24.0
    eslint-plugin-no-only-tests: ^3.3.0
    eslint-plugin-perfectionist: ^5.6.0
    eslint-plugin-pnpm: ^1.5.0
    eslint-plugin-regexp: ^3.0.0
    eslint-plugin-sonarjs: ^3.0.5
    eslint-plugin-toml: ^1.3.0
    eslint-plugin-unicorn: ^63.0.0
    eslint-plugin-unused-imports: ^4.4.1
    eslint-plugin-vue: ^10.8.0
    eslint-plugin-yml: ^3.3.0
    eslint-processor-vue-blocks: ^2.0.0
    globals: ^17.3.0
    local-pkg: ^1.1.2
    toml-eslint-parser: ^1.0.3
    vue-eslint-parser: ^10.4.0
    yaml-eslint-parser: ^2.0.0

onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
  - unrs-resolver
