packages:
  - eslint
  - docs

shamefullyHoist: true
strictPeerDependencies: false
ignoreWorkspaceRootCheck: true
useNodeVersion: 22.17.0

overrides:
  '@eslint-community/eslint-utils': ^4.9.0
  '@typescript-eslint/types': ^8.48.1
  '@typescript-eslint/utils': ^8.48.1
  eslint: ^9.39.1
  tsx: ^4.21.6
catalog:
  '@antfu/install-pkg': ^1.1.0
  '@antfu/ni': ^28.0.0
  '@clack/prompts': ^0.11.0
  '@eslint-community/eslint-plugin-eslint-comments': ^4.5.0
  '@eslint-react/eslint-plugin': ^2.3.11
  '@eslint/config-inspector': ^1.4.2
  '@eslint/markdown': ^7.5.1
  '@iconify/json': ^2.2.396
  '@prettier/plugin-xml': ^3.4.2
  '@stylistic/eslint-plugin': ^5.6.1
  '@types/node': ^24.10.1
  '@types/yargs': ^17.0.33
  '@typescript-eslint/eslint-plugin': ^8.48.1
  '@typescript-eslint/parser': ^8.48.1
  '@unocss/eslint-plugin': ^66.5.10
  '@vinicunca/perkakas': ^1.8.0
  '@vinicunca/unocss-preset': ^1.30.0
  '@vitest/eslint-plugin': ^1.3.20
  astro-eslint-parser: ^1.2.2
  bumpp: ^10.3.2
  bundle-require: ^5.1.0
  eslint: ^9.39.1
  eslint-config-flat-gitignore: ^2.1.0
  eslint-flat-config-utils: ^2.1.4
  eslint-merge-processors: ^2.0.0
  eslint-plugin-antfu: ^3.1.1
  eslint-plugin-astro: ^1.5.0
  eslint-plugin-command: ^3.3.1
  eslint-plugin-format: ^1.0.2
  eslint-plugin-import-lite: ^0.3.0
  eslint-plugin-jsdoc: ^61.4.1
  eslint-plugin-jsonc: ^2.21.0
  eslint-plugin-n: ^17.23.1
  eslint-plugin-no-only-tests: ^3.3.0
  eslint-plugin-perfectionist: ^4.15.1
  eslint-plugin-pnpm: ^1.2.0
  eslint-plugin-react-hooks: ^7.0.0
  eslint-plugin-react-refresh: ^0.4.24
  eslint-plugin-regexp: ^2.10.0
  eslint-plugin-solid: ^0.14.5
  eslint-plugin-sonarjs: ^3.0.5
  eslint-plugin-svelte: ^3.12.4
  eslint-plugin-toml: ^0.12.0
  eslint-plugin-unicorn: ^61.0.2
  eslint-plugin-unused-imports: ^4.2.0
  eslint-plugin-vue: ^10.6.2
  eslint-plugin-vuejs-accessibility: ^2.4.1
  eslint-plugin-yml: ^1.19.0
  eslint-processor-vue-blocks: ^2.0.0
  eslint-typegen: ^2.3.0
  execa: ^9.6.1
  fuse.js: ^7.1.0
  globals: ^16.5.0
  is-ci: ^4.1.0
  jiti: ^2.6.1
  jsonc-eslint-parser: ^2.4.1
  lint-staged: ^16.2.7
  local-pkg: ^1.1.2
  postcss-nested: ^7.0.2
  prettier-plugin-astro: ^0.14.1
  prettier-plugin-slidev: ^1.0.5
  radix-vue: ^1.9.17
  react: ^19.2.0
  simple-git-hooks: ^2.13.1
  svelte: ^5.45.4
  svelte-eslint-parser: ^1.3.3
  taze: ^19.8.0
  tinyglobby: ^0.2.15
  toml-eslint-parser: ^0.10.0
  tsdown: ^0.15.7
  tsx: ^4.21.0
  typescript: ^5.9.3
  unocss: 66.5.10
  unplugin-vue-components: ^29.1.0
  vitepress: ^1.6.4
  vitest: ^4.0.15
  vue: ^3.5.25
  vue-eslint-parser: ^10.2.0
  yaml-eslint-parser: ^1.3.1
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
  - unrs-resolver
