packages:
  - eslint
  - docs
overrides:
  '@eslint-community/eslint-utils': ^4.7.0
  '@typescript-eslint/types': ^8.37.0
  '@typescript-eslint/utils': ^8.37.0
  eslint: ^9.31.0
  tsx: ^4.20.3
catalog:
  '@antfu/install-pkg': ^1.1.0
  '@antfu/ni': ^25.0.0
  '@clack/prompts': ^0.11.0
  '@eslint-community/eslint-plugin-eslint-comments': ^4.5.0
  '@eslint-react/eslint-plugin': ^1.52.3
  '@eslint/config-inspector': ^1.1.0
  '@eslint/markdown': ^7.0.0
  '@iconify/json': ^2.2.324
  '@prettier/plugin-xml': ^3.4.2
  '@stylistic/eslint-plugin': ^5.0.0-beta.4
  '@types/node': ^24.0.13
  '@types/yargs': ^17.0.33
  '@typescript-eslint/eslint-plugin': ^8.37.0
  '@typescript-eslint/parser': ^8.37.0
  '@unocss/eslint-plugin': ^66.3.3
  '@vinicunca/perkakas': ^1.5.0
  '@vinicunca/unocss-preset': ^1.14.0
  '@vitest/eslint-plugin': ^1.2.7
  astro-eslint-parser: ^1.2.2
  bumpp: ^10.2.0
  bundle-require: ^5.1.0
  eslint: ^9.31.0
  eslint-config-flat-gitignore: ^2.1.0
  eslint-flat-config-utils: ^2.0.1
  eslint-merge-processors: ^2.0.0
  eslint-plugin-antfu: ^3.1.1
  eslint-plugin-astro: ^1.3.1
  eslint-plugin-command: ^3.2.1
  eslint-plugin-format: ^1.0.1
  eslint-plugin-import-lite: ^0.3.0
  eslint-plugin-jsdoc: ^51.3.4
  eslint-plugin-jsonc: ^2.20.1
  eslint-plugin-n: ^17.21.0
  eslint-plugin-no-only-tests: ^3.3.0
  eslint-plugin-perfectionist: ^4.15.0
  eslint-plugin-pnpm: ^1.0.0
  eslint-plugin-react-hooks: ^5.2.0
  eslint-plugin-react-refresh: ^0.4.20
  eslint-plugin-regexp: ^2.9.0
  eslint-plugin-solid: ^0.14.5
  eslint-plugin-sonarjs: ^3.0.2
  eslint-plugin-svelte: ^3.9.2
  eslint-plugin-toml: ^0.12.0
  eslint-plugin-unicorn: ^59.0.1
  eslint-plugin-unused-imports: ^4.1.4
  eslint-plugin-vue: ^10.3.0
  eslint-plugin-vuejs-accessibility: ^2.4.1
  eslint-plugin-yml: ^1.18.0
  eslint-processor-vue-blocks: ^2.0.0
  eslint-typegen: ^2.2.0
  execa: ^9.6.0
  fuse.js: ^7.1.0
  globals: ^16.2.0
  is-ci: ^4.1.0
  jiti: ^2.4.2
  jsonc-eslint-parser: ^2.4.0
  lint-staged: ^16.1.2
  local-pkg: ^1.1.1
  postcss-nested: ^7.0.2
  prettier-plugin-astro: ^0.14.1
  prettier-plugin-slidev: ^1.0.5
  radix-vue: ^1.9.17
  react: ^19.1.0
  simple-git-hooks: ^2.13.0
  svelte: ^5.36.0
  svelte-eslint-parser: ^1.2.0
  taze: ^19.0.4
  tinyglobby: ^0.2.14
  toml-eslint-parser: ^0.10.0
  tsdown: ^0.12.8
  tsx: ^4.20.3
  typescript: ^5.8.3
  unocss: 66.0.0
  unplugin-vue-components: ^28.4.1
  vitepress: ^1.6.3
  vitest: ^3.2.4
  vue: ^3.5.17
  vue-eslint-parser: ^10.1.3
  yaml-eslint-parser: ^1.3.0
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
  - unrs-resolver
