packages:
  - eslint
  - docs
overrides:
  '@eslint-community/eslint-utils': ^4.7.0
  '@typescript-eslint/utils': ^8.32.1
  eslint: ^9.26.0
  tsx: ^4.19.4
catalog:
  '@antfu/install-pkg': ^1.1.0
  '@antfu/ni': ^24.3.0
  '@clack/prompts': ^0.10.1
  '@eslint-community/eslint-plugin-eslint-comments': ^4.5.0
  '@eslint-react/eslint-plugin': ^1.49.0
  '@eslint/config-inspector': ^1.0.2
  '@eslint/markdown': ^6.4.0
  '@iconify/json': ^2.2.324
  '@prettier/plugin-xml': ^3.4.1
  '@stylistic/eslint-plugin': ^4.2.0
  '@stylistic/eslint-plugin-migrate': ^4.2.0
  '@types/node': ^22.15.18
  '@types/yargs': ^17.0.33
  '@typescript-eslint/eslint-plugin': ^8.32.1
  '@typescript-eslint/parser': ^8.32.1
  '@unocss/eslint-plugin': 66.0.0
  '@vinicunca/perkakas': ^1.5.0
  '@vinicunca/unocss-preset': ^1.14.0
  '@vitest/eslint-plugin': ^1.1.44
  astro-eslint-parser: ^1.2.2
  bumpp: ^10.1.1
  bundle-require: ^5.1.0
  eslint: ^9.26.0
  eslint-config-flat-gitignore: ^2.1.0
  eslint-flat-config-utils: ^2.0.1
  eslint-merge-processors: ^2.0.0
  eslint-plugin-antfu: ^3.1.1
  eslint-plugin-astro: ^1.3.1
  eslint-plugin-command: ^3.2.0
  eslint-plugin-format: ^1.0.1
  eslint-plugin-import-x: ^4.11.1
  eslint-plugin-jsdoc: ^50.6.17
  eslint-plugin-jsonc: ^2.20.0
  eslint-plugin-n: ^17.18.0
  eslint-plugin-no-only-tests: ^3.3.0
  eslint-plugin-perfectionist: ^4.13.0
  eslint-plugin-pnpm: ^0.3.1
  eslint-plugin-react-hooks: ^5.2.0
  eslint-plugin-react-refresh: ^0.4.20
  eslint-plugin-regexp: ^2.7.0
  eslint-plugin-solid: ^0.14.5
  eslint-plugin-sonarjs: ^3.0.2
  eslint-plugin-svelte: ^3.7.0
  eslint-plugin-toml: ^0.12.0
  eslint-plugin-unicorn: ^59.0.1
  eslint-plugin-unused-imports: ^4.1.4
  eslint-plugin-vue: ^10.1.0
  eslint-plugin-vuejs-accessibility: ^2.4.1
  eslint-plugin-yml: ^1.18.0
  eslint-processor-vue-blocks: ^2.0.0
  eslint-typegen: ^2.2.0
  execa: ^9.5.2
  fuse.js: ^7.1.0
  globals: ^16.1.0
  is-ci: ^4.1.0
  jiti: ^2.4.2
  jsonc-eslint-parser: ^2.4.0
  lint-staged: ^16.0.0
  local-pkg: ^1.1.1
  postcss-nested: ^7.0.2
  prettier-plugin-astro: ^0.14.1
  prettier-plugin-slidev: ^1.0.5
  radix-vue: ^1.9.17
  react: ^19.1.0
  simple-git-hooks: ^2.13.0
  svelte: ^5.30.1
  svelte-eslint-parser: ^1.2.0
  taze: ^19.0.4
  tinyglobby: ^0.2.13
  toml-eslint-parser: ^0.10.0
  tsup: ^8.4.0
  tsx: ^4.19.4
  typescript: ^5.8.3
  unocss: 66.0.0
  unplugin-vue-components: ^28.4.1
  vitepress: ^1.6.3
  vitest: ^3.1.3
  vue: ^3.5.14
  vue-eslint-parser: ^10.1.3
  yaml-eslint-parser: ^1.3.0
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
  - unrs-resolver
