[
  "<ignored>",
  "<ignored>",
  {
    "name": "vinicunca/javascript/rules",
    "plugins": [
      "antfu",
      "unused-imports",
    ],
    "rules": [
      "accessor-pairs",
      "antfu/no-top-level-await",
      "array-callback-return",
      "block-scoped-var",
      "camelcase",
      "constructor-super",
      "default-case-last",
      "dot-notation",
      "eqeqeq",
      "for-direction",
      "new-cap",
      "no-alert",
      "no-array-constructor",
      "no-async-promise-executor",
      "no-await-in-loop",
      "no-caller",
      "no-case-declarations",
      "no-class-assign",
      "no-compare-neg-zero",
      "no-cond-assign",
      "no-console",
      "no-const-assign",
      "no-constant-binary-expression",
      "no-constant-condition",
      "no-constructor-return",
      "no-control-regex",
      "no-debugger",
      "no-delete-var",
      "no-dupe-args",
      "no-dupe-class-members",
      "no-dupe-else-if",
      "no-dupe-keys",
      "no-duplicate-case",
      "no-empty",
      "no-empty-character-class",
      "no-empty-pattern",
      "no-eval",
      "no-ex-assign",
      "no-extend-native",
      "no-extra-bind",
      "no-extra-boolean-cast",
      "no-fallthrough",
      "no-func-assign",
      "no-global-assign",
      "no-implied-eval",
      "no-import-assign",
      "no-invalid-regexp",
      "no-irregular-whitespace",
      "no-iterator",
      "no-labels",
      "no-lone-blocks",
      "no-loss-of-precision",
      "no-misleading-character-class",
      "no-multi-str",
      "no-nested-ternary",
      "no-new",
      "no-new-func",
      "no-new-native-nonconstructor",
      "no-new-wrappers",
      "no-obj-calls",
      "no-object-constructor",
      "no-octal",
      "no-octal-escape",
      "no-promise-executor-return",
      "no-proto",
      "no-prototype-builtins",
      "no-redeclare",
      "no-regex-spaces",
      "no-restricted-globals",
      "no-restricted-properties",
      "no-restricted-syntax",
      "no-return-assign",
      "no-self-assign",
      "no-self-compare",
      "no-sequences",
      "no-shadow-restricted-names",
      "no-sparse-arrays",
      "no-template-curly-in-string",
      "no-this-before-super",
      "no-throw-literal",
      "no-undef",
      "no-undef-init",
      "no-unexpected-multiline",
      "no-unmodified-loop-condition",
      "no-unneeded-ternary",
      "no-unreachable",
      "no-unreachable-loop",
      "no-unsafe-finally",
      "no-unsafe-negation",
      "no-unused-expressions",
      "no-unused-vars",
      "no-use-before-define",
      "no-useless-backreference",
      "no-useless-call",
      "no-useless-catch",
      "no-useless-computed-key",
      "no-useless-constructor",
      "no-useless-rename",
      "no-useless-return",
      "no-var",
      "no-with",
      "object-shorthand",
      "one-var",
      "prefer-arrow-callback",
      "prefer-const",
      "prefer-exponentiation-operator",
      "prefer-promise-reject-errors",
      "prefer-regex-literals",
      "prefer-rest-params",
      "prefer-spread",
      "prefer-template",
      "symbol-description",
      "unicode-bom",
      "unused-imports/no-unused-imports",
      "unused-imports/no-unused-vars",
      "use-isnan",
      "valid-typeof",
      "vars-on-top",
      "yoda",
    ],
  },
  {
    "name": "vinicunca/eslint-comments/rules",
    "plugins": [
      "eslint-comments",
    ],
    "rules": [
      "eslint-comments/no-aggregating-enable",
      "eslint-comments/no-duplicate-disable",
      "eslint-comments/no-unlimited-disable",
      "eslint-comments/no-unused-enable",
    ],
  },
  {
    "name": "vinicunca/imports/rules",
    "plugins": [
      "antfu",
      "import",
    ],
    "rules": [
      "antfu/import-dedupe",
      "antfu/no-import-dist",
      "antfu/no-import-node-modules-by-path",
      "import/consistent-type-specifier-style",
      "import/first",
      "import/no-duplicates",
      "import/no-mutable-exports",
      "import/no-named-default",
    ],
  },
  {
    "name": "vinicunca/command/rules",
    "plugins": [
      "command",
    ],
    "rules": [
      "command/command",
    ],
  },
  {
    "name": "vinicunca/perfectionist/rules",
    "plugins": [
      "perfectionist",
    ],
    "rules": [
      "perfectionist/sort-exports",
      "perfectionist/sort-imports",
      "perfectionist/sort-named-exports",
      "perfectionist/sort-named-imports",
    ],
  },
  {
    "name": "vinicunca/sonar/rules",
    "plugins": [
      "sonar",
    ],
    "rules": [
      "- sonar/function-name",
      "sonar/class-name",
      "- sonar/max-lines",
      "- sonar/no-tab",
      "- sonar/variable-name",
      "- sonar/comment-regex",
      "sonar/no-commented-code",
      "- sonar/elseif-without-else",
      "sonar/no-fallthrough",
      "- sonar/nested-control-flow",
      "- sonar/too-many-break-or-continue-in-loop",
      "- sonar/max-lines-per-function",
      "- sonar/no-nested-incdec",
      "sonar/no-equals-in-for-termination",
      "sonar/no-extra-arguments",
      "- sonar/no-collapsible-if",
      "- sonar/expression-complexity",
      "- sonar/no-redundant-parentheses",
      "sonar/no-labels",
      "sonar/no-nested-assignment",
      "sonar/no-redundant-boolean",
      "sonar/prefer-single-boolean-return",
      "sonar/unused-import",
      "sonar/fixme-tag",
      "- sonar/todo-tag",
      "- sonar/useless-string-operation",
      "- sonar/no-unused-function-argument",
      "- sonar/no-duplicate-string",
      "sonar/no-case-label-in-switch",
      "sonar/no-parameter-reassignment",
      "sonar/prefer-while",
      "- sonar/no-sonar-comments",
      "sonar/no-small-switch",
      "sonar/no-hardcoded-ip",
      "sonar/label-position",
      "sonar/public-static-readonly",
      "- sonar/file-header",
      "sonar/call-argument-line",
      "sonar/max-switch-cases",
      "- sonar/no-unused-vars",
      "- sonar/prefer-immediate-return",
      "sonar/function-inside-loop",
      "sonar/code-eval",
      "- sonar/no-variable-usage-before-declaration",
      "sonar/future-reserved-words",
      "- sonar/array-constructor",
      "sonar/bitwise-operators",
      "- sonar/no-function-declaration-in-block",
      "sonar/no-primitive-wrappers",
      "- sonar/for-in",
      "- sonar/cyclomatic-complexity",
      "sonar/no-skipped-tests",
      "sonar/no-identical-expressions",
      "- sonar/no-nested-switch",
      "sonar/constructor-for-side-effects",
      "sonar/no-dead-store",
      "sonar/no-identical-conditions",
      "sonar/no-duplicated-branches",
      "sonar/deprecation",
      "sonar/no-inverted-boolean-check",
      "sonar/misplaced-loop-counter",
      "sonar/no-nested-functions",
      "sonar/no-hardcoded-passwords",
      "sonar/sql-queries",
      "sonar/insecure-cookie",
      "sonar/no-useless-increment",
      "sonar/no-globals-shadowing",
      "- sonar/no-undefined-assignment",
      "sonar/no-empty-test-file",
      "sonar/no-ignored-return",
      "- sonar/no-wildcard-import",
      "sonar/arguments-order",
      "- sonar/pseudo-random",
      "sonar/for-loop-increment-sign",
      "- sonar/cookies",
      "sonar/null-dereference",
      "sonar/no-selector-parameter",
      "sonar/updated-loop-counter",
      "sonar/block-scoped-var",
      "- sonar/no-built-in-override",
      "- sonar/prefer-object-literal",
      "sonar/no-ignored-exceptions",
      "sonar/no-gratuitous-expressions",
      "sonar/file-uploads",
      "sonar/file-permissions",
      "sonar/no-empty-character-class",
      "sonar/no-unenclosed-multiline-block",
      "sonar/index-of-compare-to-positive-number",
      "sonar/assertions-in-tests",
      "sonar/no-implicit-global",
      "sonar/no-useless-catch",
      "sonar/xml-parser-xxe",
      "sonar/non-existent-operator",
      "- sonar/web-sql-database",
      "sonar/post-message",
      "sonar/no-array-delete",
      "sonar/no-alphabetical-sort",
      "sonar/no-incomplete-assertions",
      "sonar/no-global-this",
      "sonar/new-operator-misuse",
      "sonar/no-delete-var",
      "- sonar/strings-comparison",
      "- sonar/file-name-differ-from-class",
      "sonar/cookie-no-httponly",
      "sonar/no-nested-conditional",
      "- sonar/no-incorrect-string-concat",
      "sonar/different-types-comparison",
      "sonar/inverted-assertion-arguments",
      "- sonar/shorthand-property-grouping",
      "sonar/updated-const-var",
      "- sonar/arguments-usage",
      "- sonar/destructuring-assignment-syntax",
      "sonar/no-invariant-returns",
      "- sonar/arrow-function-convention",
      "- sonar/class-prototype",
      "sonar/generator-without-yield",
      "- sonar/no-require-or-define",
      "sonar/no-associative-arrays",
      "sonar/comma-or-logical-or-case",
      "sonar/no-redundant-jump",
      "sonar/inconsistent-function-call",
      "sonar/no-use-of-empty-return-value",
      "- sonar/enforce-trailing-comma",
      "sonar/void-use",
      "- sonar/operation-returning-nan",
      "- sonar/values-not-convertible-to-numbers",
      "- sonar/non-number-in-arithmetic-expression",
      "- sonar/cognitive-complexity",
      "sonar/argument-type",
      "sonar/in-operator-type-error",
      "sonar/array-callback-without-return",
      "- sonar/declarations-in-global-scope",
      "sonar/function-return-type",
      "- sonar/no-inconsistent-returns",
      "- sonar/no-reference-error",
      "sonar/super-invocation",
      "sonar/no-all-duplicated-branches",
      "sonar/no-same-line-conditional",
      "- sonar/conditional-indentation",
      "sonar/no-collection-size-mischeck",
      "sonar/no-unthrown-error",
      "sonar/no-unused-collection",
      "sonar/no-os-command-from-path",
      "sonar/no-misleading-array-reverse",
      "- sonar/no-for-in-iterable",
      "sonar/no-element-overwrite",
      "sonar/no-identical-functions",
      "sonar/no-empty-collection",
      "sonar/no-redundant-assignments",
      "sonar/prefer-type-guard",
      "sonar/use-type-alias",
      "- sonar/no-return-type-any",
      "- sonar/no-implicit-dependencies",
      "sonar/no-useless-intersection",
      "sonar/weak-ssl",
      "sonar/no-weak-keys",
      "sonar/csrf",
      "sonar/production-debug",
      "sonar/prefer-default-last",
      "sonar/no-in-misuse",
      "sonar/no-duplicate-in-composite",
      "- sonar/max-union-size",
      "sonar/no-undefined-argument",
      "sonar/no-nested-template-literals",
      "sonar/prefer-promise-shorthand",
      "sonar/os-command",
      "sonar/no-redundant-optional",
      "- sonar/regular-expr",
      "- sonar/encryption",
      "sonar/hashing",
      "- sonar/bool-param-default",
      "- sonar/xpath",
      "- sonar/sockets",
      "sonar/no-try-promise",
      "- sonar/process-argv",
      "- sonar/standard-input",
      "sonar/unverified-certificate",
      "sonar/no-unsafe-unzip",
      "sonar/cors",
      "sonar/link-with-target-blank",
      "sonar/disabled-auto-escaping",
      "sonar/table-header",
      "sonar/no-table-as-layout",
      "sonar/table-header-reference",
      "sonar/object-alt-content",
      "sonar/no-clear-text-protocols",
      "sonar/publicly-writable-directories",
      "sonar/unverified-hostname",
      "sonar/encryption-secure-mode",
      "sonar/no-weak-cipher",
      "sonar/no-intrusive-permissions",
      "sonar/insecure-jwt-token",
      "sonar/x-powered-by",
      "sonar/hidden-files",
      "sonar/content-length",
      "sonar/disabled-resource-integrity",
      "sonar/content-security-policy",
      "sonar/no-mixed-content",
      "sonar/frame-ancestors",
      "sonar/no-mime-sniff",
      "sonar/no-referrer-policy",
      "sonar/strict-transport-security",
      "- sonar/certificate-transparency",
      "- sonar/dns-prefetching",
      "sonar/confidential-information-logging",
      "sonar/no-ip-forward",
      "sonar/empty-string-repetition",
      "sonar/regex-complexity",
      "sonar/anchor-precedence",
      "- sonar/slow-regex",
      "sonar/no-invalid-regexp",
      "sonar/unused-named-groups",
      "sonar/no-same-argument-assert",
      "- sonar/unicode-aware-regex",
      "sonar/no-misleading-character-class",
      "sonar/duplicates-in-character-class",
      "sonar/session-regeneration",
      "sonar/test-check-exception",
      "sonar/stable-tests",
      "sonar/no-empty-after-reluctant",
      "sonar/single-character-alternation",
      "sonar/no-code-after-done",
      "sonar/disabled-timeout",
      "sonar/chai-determinate-assertion",
      "- sonar/aws-s3-bucket-server-encryption",
      "sonar/aws-s3-bucket-insecure-http",
      "sonar/aws-s3-bucket-versioning",
      "sonar/aws-s3-bucket-granted-access",
      "sonar/no-angular-bypass-sanitization",
      "sonar/aws-iam-public-access",
      "sonar/aws-ec2-unencrypted-ebs-volume",
      "sonar/aws-s3-bucket-public-access",
      "- sonar/no-vue-bypass-sanitization",
      "sonar/aws-iam-all-privileges",
      "sonar/aws-rds-unencrypted-databases",
      "- sonar/aws-iam-all-resources-accessible",
      "sonar/aws-opensearchservice-domain",
      "sonar/aws-iam-privilege-escalation",
      "sonar/aws-sagemaker-unencrypted-notebook",
      "sonar/aws-restricted-ip-admin-access",
      "sonar/no-empty-alternatives",
      "sonar/no-control-regex",
      "sonar/no-regex-spaces",
      "sonar/aws-sns-unencrypted-topics",
      "sonar/existing-groups",
      "sonar/aws-ec2-rds-dms-public",
      "sonar/aws-sqs-unencrypted-queue",
      "sonar/no-empty-group",
      "sonar/aws-efs-unencrypted",
      "sonar/aws-apigateway-public-api",
      "sonar/stateful-regex",
      "sonar/concise-regex",
      "sonar/single-char-in-character-classes",
      "sonar/no-hardcoded-secrets",
      "sonar/no-exclusive-tests",
      "sonar/jsx-no-leaked-render",
      "sonar/no-hook-setter-in-body",
      "sonar/no-useless-react-setstate",
      "sonar/no-uniq-key",
      "sonar/redundant-type-aliases",
      "sonar/prefer-regexp-exec",
      "sonar/no-internal-api-use",
      "sonar/prefer-read-only-props",
      "sonar/no-literal-call",
      "sonar/reduce-initial-value",
      "sonar/no-async-constructor",
    ],
  },
  {
    "files": [
      "**/scripts/**/*.?([cm])[jt]s?(x)",
    ],
    "name": "vinicunca/disables/scripts",
    "rules": [
      "- antfu/no-top-level-await",
      "- no-console",
      "- ts/explicit-function-return-type",
    ],
  },
  {
    "files": [
      "**/cli/**/*.?([cm])[jt]s?(x)",
      "**/cli.?([cm])[jt]s?(x)",
    ],
    "name": "vinicunca/disables/cli",
    "rules": [
      "- antfu/no-top-level-await",
      "- no-console",
    ],
  },
  {
    "files": [
      "**/bin/**/*",
      "**/bin.?([cm])[jt]s?(x)",
    ],
    "name": "vinicunca/disables/bin",
    "rules": [
      "- antfu/no-import-dist",
      "- antfu/no-import-node-modules-by-path",
    ],
  },
  {
    "files": [
      "**/*.d.?([cm])ts",
    ],
    "name": "vinicunca/disables/dts",
    "rules": [
      "- eslint-comments/no-unlimited-disable",
      "- no-restricted-syntax",
      "- unused-imports/no-unused-vars",
    ],
  },
  {
    "files": [
      "**/*.js",
      "**/*.cjs",
    ],
    "name": "vinicunca/disables/cjs",
    "rules": [
      "- ts/no-require-imports",
    ],
  },
  {
    "files": [
      "**/*.config.?([cm])[jt]s?(x)",
      "**/*.config.*.?([cm])[jt]s?(x)",
    ],
    "name": "vinicunca/disables/config-files",
    "rules": [
      "- antfu/no-top-level-await",
      "- no-console",
      "- ts/explicit-function-return-type",
    ],
  },
]