[
  "<ignored>",
  "<ignored>",
  "<ignored>",
  {
    "name": "vinicunca/javascript/rules",
    "plugins": [
      "antfu",
      "unused-imports",
    ],
    "rules": [
      "accessor-pairs",
      "antfu/no-top-level-await",
      "array-callback-return",
      "block-scoped-var",
      "camelcase",
      "constructor-super",
      "default-case-last",
      "dot-notation",
      "eqeqeq",
      "for-direction",
      "new-cap",
      "no-alert",
      "no-array-constructor",
      "no-async-promise-executor",
      "no-await-in-loop",
      "no-caller",
      "no-case-declarations",
      "no-class-assign",
      "no-compare-neg-zero",
      "no-cond-assign",
      "no-console",
      "no-const-assign",
      "no-constant-binary-expression",
      "no-constant-condition",
      "no-constructor-return",
      "no-control-regex",
      "no-debugger",
      "no-delete-var",
      "no-dupe-args",
      "no-dupe-class-members",
      "no-dupe-else-if",
      "no-dupe-keys",
      "no-duplicate-case",
      "no-empty",
      "no-empty-character-class",
      "no-empty-pattern",
      "no-eval",
      "no-ex-assign",
      "no-extend-native",
      "no-extra-bind",
      "no-extra-boolean-cast",
      "no-fallthrough",
      "no-func-assign",
      "no-global-assign",
      "no-implied-eval",
      "no-import-assign",
      "no-invalid-regexp",
      "no-irregular-whitespace",
      "no-iterator",
      "no-labels",
      "no-lone-blocks",
      "no-loss-of-precision",
      "no-misleading-character-class",
      "no-multi-str",
      "no-nested-ternary",
      "no-new",
      "no-new-func",
      "no-new-native-nonconstructor",
      "no-new-wrappers",
      "no-obj-calls",
      "no-object-constructor",
      "no-octal",
      "no-octal-escape",
      "no-promise-executor-return",
      "no-proto",
      "no-prototype-builtins",
      "no-redeclare",
      "no-regex-spaces",
      "no-restricted-globals",
      "no-restricted-properties",
      "no-restricted-syntax",
      "no-return-assign",
      "no-self-assign",
      "no-self-compare",
      "no-sequences",
      "no-shadow-restricted-names",
      "no-sparse-arrays",
      "no-template-curly-in-string",
      "no-this-before-super",
      "no-throw-literal",
      "no-undef",
      "no-undef-init",
      "no-unexpected-multiline",
      "no-unmodified-loop-condition",
      "no-unneeded-ternary",
      "no-unreachable",
      "no-unreachable-loop",
      "no-unsafe-finally",
      "no-unsafe-negation",
      "no-unused-expressions",
      "no-unused-vars",
      "no-use-before-define",
      "no-useless-backreference",
      "no-useless-call",
      "no-useless-catch",
      "no-useless-computed-key",
      "no-useless-constructor",
      "no-useless-rename",
      "no-useless-return",
      "no-var",
      "no-with",
      "object-shorthand",
      "one-var",
      "prefer-arrow-callback",
      "prefer-const",
      "prefer-exponentiation-operator",
      "prefer-promise-reject-errors",
      "prefer-regex-literals",
      "prefer-rest-params",
      "prefer-spread",
      "prefer-template",
      "symbol-description",
      "unicode-bom",
      "unused-imports/no-unused-imports",
      "unused-imports/no-unused-vars",
      "use-isnan",
      "valid-typeof",
      "vars-on-top",
      "yoda",
    ],
  },
  {
    "name": "vinicunca/eslint-comments/rules",
    "plugins": [
      "eslint-comments",
    ],
    "rules": [
      "eslint-comments/no-aggregating-enable",
      "eslint-comments/no-duplicate-disable",
      "eslint-comments/no-unlimited-disable",
      "eslint-comments/no-unused-enable",
    ],
  },
  {
    "name": "vinicunca/imports/rules",
    "plugins": [
      "antfu",
      "import",
    ],
    "rules": [
      "antfu/import-dedupe",
      "antfu/no-import-dist",
      "antfu/no-import-node-modules-by-path",
      "import/consistent-type-specifier-style",
      "import/first",
      "import/no-duplicates",
      "import/no-mutable-exports",
      "import/no-named-default",
      "import/newline-after-import",
    ],
  },
  {
    "name": "vinicunca/command/rules",
    "plugins": [
      "command",
    ],
    "rules": [
      "command/command",
    ],
  },
  {
    "name": "vinicunca/perfectionist/rules",
    "plugins": [
      "perfectionist",
    ],
    "rules": [
      "perfectionist/sort-exports",
      "perfectionist/sort-imports",
      "perfectionist/sort-named-exports",
      "perfectionist/sort-named-imports",
    ],
  },
  {
    "name": "vinicunca/sonar/rules",
    "plugins": [
      "sonar",
    ],
    "rules": [
      "- sonar/function-name",
      "sonar/class-name",
      "- sonar/max-lines",
      "- sonar/no-tab",
      "- sonar/variable-name",
      "- sonar/comment-regex",
      "sonar/no-commented-code",
      "- sonar/elseif-without-else",
      "sonar/no-fallthrough",
      "- sonar/nested-control-flow",
      "- sonar/too-many-break-or-continue-in-loop",
      "- sonar/max-lines-per-function",
      "- sonar/no-nested-incdec",
      "sonar/no-equals-in-for-termination",
      "sonar/no-extra-arguments",
      "- sonar/no-collapsible-if",
      "- sonar/expression-complexity",
      "- sonar/no-redundant-parentheses",
      "sonar/no-labels",
      "sonar/no-nested-assignment",
      "sonar/no-redundant-boolean",
      "sonar/prefer-single-boolean-return",
      "sonar/unused-import",
      "sonar/fixme-tag",
      "- sonar/todo-tag",
      "- sonar/useless-string-operation",
      "- sonar/no-unused-function-argument",
      "- sonar/no-duplicate-string",
      "sonar/no-case-label-in-switch",
      "sonar/no-parameter-reassignment",
      "sonar/prefer-while",
      "- sonar/no-sonar-comments",
      "sonar/no-small-switch",
      "sonar/no-hardcoded-ip",
      "sonar/label-position",
      "sonar/public-static-readonly",
      "- sonar/file-header",
      "sonar/call-argument-line",
      "sonar/max-switch-cases",
      "- sonar/no-unused-vars",
      "- sonar/prefer-immediate-return",
      "sonar/function-inside-loop",
      "sonar/code-eval",
      "- sonar/no-variable-usage-before-declaration",
      "sonar/future-reserved-words",
      "- sonar/array-constructor",
      "sonar/bitwise-operators",
      "- sonar/no-function-declaration-in-block",
      "sonar/no-primitive-wrappers",
      "- sonar/for-in",
      "- sonar/cyclomatic-complexity",
      "sonar/no-skipped-tests",
      "sonar/no-identical-expressions",
      "- sonar/no-nested-switch",
      "sonar/constructor-for-side-effects",
      "sonar/no-dead-store",
      "sonar/no-identical-conditions",
      "sonar/no-duplicated-branches",
      "sonar/deprecation",
      "sonar/no-inverted-boolean-check",
      "sonar/misplaced-loop-counter",
      "sonar/no-nested-functions",
      "sonar/no-hardcoded-passwords",
      "sonar/sql-queries",
      "sonar/insecure-cookie",
      "sonar/no-useless-increment",
      "sonar/no-globals-shadowing",
      "- sonar/no-undefined-assignment",
      "sonar/no-empty-test-file",
      "sonar/no-ignored-return",
      "- sonar/no-wildcard-import",
      "sonar/arguments-order",
      "- sonar/pseudo-random",
      "sonar/for-loop-increment-sign",
      "- sonar/cookies",
      "sonar/null-dereference",
      "sonar/no-selector-parameter",
      "sonar/updated-loop-counter",
      "sonar/block-scoped-var",
      "- sonar/no-built-in-override",
      "- sonar/prefer-object-literal",
      "sonar/no-ignored-exceptions",
      "sonar/no-gratuitous-expressions",
      "sonar/file-uploads",
      "sonar/file-permissions",
      "sonar/no-empty-character-class",
      "sonar/no-unenclosed-multiline-block",
      "sonar/index-of-compare-to-positive-number",
      "sonar/assertions-in-tests",
      "sonar/no-implicit-global",
      "sonar/no-useless-catch",
      "sonar/xml-parser-xxe",
      "sonar/non-existent-operator",
      "- sonar/web-sql-database",
      "sonar/post-message",
      "sonar/no-array-delete",
      "sonar/no-alphabetical-sort",
      "sonar/no-incomplete-assertions",
      "sonar/no-global-this",
      "sonar/new-operator-misuse",
      "sonar/no-delete-var",
      "- sonar/strings-comparison",
      "- sonar/file-name-differ-from-class",
      "sonar/cookie-no-httponly",
      "sonar/no-nested-conditional",
      "- sonar/no-incorrect-string-concat",
      "sonar/different-types-comparison",
      "sonar/inverted-assertion-arguments",
      "- sonar/shorthand-property-grouping",
      "sonar/updated-const-var",
      "- sonar/arguments-usage",
      "- sonar/destructuring-assignment-syntax",
      "sonar/no-invariant-returns",
      "- sonar/arrow-function-convention",
      "- sonar/class-prototype",
      "sonar/generator-without-yield",
      "- sonar/no-require-or-define",
      "sonar/no-associative-arrays",
      "sonar/comma-or-logical-or-case",
      "sonar/no-redundant-jump",
      "sonar/inconsistent-function-call",
      "sonar/no-use-of-empty-return-value",
      "- sonar/enforce-trailing-comma",
      "sonar/void-use",
      "- sonar/operation-returning-nan",
      "- sonar/values-not-convertible-to-numbers",
      "- sonar/non-number-in-arithmetic-expression",
      "- sonar/cognitive-complexity",
      "sonar/argument-type",
      "sonar/in-operator-type-error",
      "sonar/array-callback-without-return",
      "- sonar/declarations-in-global-scope",
      "sonar/function-return-type",
      "- sonar/no-inconsistent-returns",
      "- sonar/no-reference-error",
      "sonar/super-invocation",
      "sonar/no-all-duplicated-branches",
      "sonar/no-same-line-conditional",
      "- sonar/conditional-indentation",
      "sonar/no-collection-size-mischeck",
      "sonar/no-unthrown-error",
      "sonar/no-unused-collection",
      "sonar/no-os-command-from-path",
      "sonar/no-misleading-array-reverse",
      "- sonar/no-for-in-iterable",
      "sonar/no-element-overwrite",
      "sonar/no-identical-functions",
      "sonar/no-empty-collection",
      "sonar/no-redundant-assignments",
      "sonar/prefer-type-guard",
      "sonar/use-type-alias",
      "- sonar/no-return-type-any",
      "- sonar/no-implicit-dependencies",
      "sonar/no-useless-intersection",
      "sonar/weak-ssl",
      "sonar/no-weak-keys",
      "sonar/csrf",
      "sonar/production-debug",
      "sonar/prefer-default-last",
      "sonar/no-in-misuse",
      "sonar/no-duplicate-in-composite",
      "- sonar/max-union-size",
      "sonar/no-undefined-argument",
      "sonar/no-nested-template-literals",
      "sonar/prefer-promise-shorthand",
      "sonar/os-command",
      "sonar/no-redundant-optional",
      "- sonar/regular-expr",
      "- sonar/encryption",
      "sonar/hashing",
      "- sonar/bool-param-default",
      "- sonar/xpath",
      "- sonar/sockets",
      "sonar/no-try-promise",
      "- sonar/process-argv",
      "- sonar/standard-input",
      "sonar/unverified-certificate",
      "sonar/no-unsafe-unzip",
      "sonar/cors",
      "sonar/link-with-target-blank",
      "sonar/disabled-auto-escaping",
      "sonar/table-header",
      "sonar/no-table-as-layout",
      "sonar/table-header-reference",
      "sonar/object-alt-content",
      "sonar/no-clear-text-protocols",
      "sonar/publicly-writable-directories",
      "sonar/unverified-hostname",
      "sonar/encryption-secure-mode",
      "sonar/no-weak-cipher",
      "sonar/no-intrusive-permissions",
      "sonar/insecure-jwt-token",
      "sonar/x-powered-by",
      "sonar/hidden-files",
      "sonar/content-length",
      "sonar/disabled-resource-integrity",
      "sonar/content-security-policy",
      "sonar/no-mixed-content",
      "sonar/frame-ancestors",
      "sonar/no-mime-sniff",
      "sonar/no-referrer-policy",
      "sonar/strict-transport-security",
      "- sonar/certificate-transparency",
      "- sonar/dns-prefetching",
      "sonar/confidential-information-logging",
      "sonar/no-ip-forward",
      "sonar/empty-string-repetition",
      "sonar/regex-complexity",
      "sonar/anchor-precedence",
      "- sonar/slow-regex",
      "sonar/no-invalid-regexp",
      "sonar/unused-named-groups",
      "sonar/no-same-argument-assert",
      "- sonar/unicode-aware-regex",
      "sonar/no-misleading-character-class",
      "sonar/duplicates-in-character-class",
      "sonar/session-regeneration",
      "sonar/test-check-exception",
      "sonar/stable-tests",
      "sonar/no-empty-after-reluctant",
      "sonar/single-character-alternation",
      "sonar/no-code-after-done",
      "sonar/disabled-timeout",
      "sonar/chai-determinate-assertion",
      "- sonar/aws-s3-bucket-server-encryption",
      "sonar/aws-s3-bucket-insecure-http",
      "sonar/aws-s3-bucket-versioning",
      "sonar/aws-s3-bucket-granted-access",
      "sonar/no-angular-bypass-sanitization",
      "sonar/aws-iam-public-access",
      "sonar/aws-ec2-unencrypted-ebs-volume",
      "sonar/aws-s3-bucket-public-access",
      "- sonar/no-vue-bypass-sanitization",
      "sonar/aws-iam-all-privileges",
      "sonar/aws-rds-unencrypted-databases",
      "- sonar/aws-iam-all-resources-accessible",
      "sonar/aws-opensearchservice-domain",
      "sonar/aws-iam-privilege-escalation",
      "sonar/aws-sagemaker-unencrypted-notebook",
      "sonar/aws-restricted-ip-admin-access",
      "sonar/no-empty-alternatives",
      "sonar/no-control-regex",
      "sonar/no-regex-spaces",
      "sonar/aws-sns-unencrypted-topics",
      "sonar/existing-groups",
      "sonar/aws-ec2-rds-dms-public",
      "sonar/aws-sqs-unencrypted-queue",
      "sonar/no-empty-group",
      "sonar/aws-efs-unencrypted",
      "sonar/aws-apigateway-public-api",
      "sonar/stateful-regex",
      "sonar/concise-regex",
      "sonar/single-char-in-character-classes",
      "sonar/no-hardcoded-secrets",
      "sonar/no-exclusive-tests",
      "sonar/jsx-no-leaked-render",
      "sonar/no-hook-setter-in-body",
      "sonar/no-useless-react-setstate",
      "sonar/no-uniq-key",
      "sonar/redundant-type-aliases",
      "sonar/prefer-regexp-exec",
      "sonar/no-internal-api-use",
      "sonar/prefer-read-only-props",
      "sonar/no-literal-call",
      "sonar/reduce-initial-value",
      "sonar/no-async-constructor",
    ],
  },
  {
    "name": "vinicunca/node/rules",
    "plugins": [
      "node",
    ],
    "rules": [
      "node/handle-callback-err",
      "- node/no-callback-literal",
      "node/no-deprecated-api",
      "node/no-exports-assign",
      "node/no-new-require",
      "node/no-path-concat",
      "node/prefer-global/buffer",
      "node/prefer-global/process",
      "node/process-exit-as-throw",
    ],
  },
  {
    "name": "vinicunca/jsdoc/setup",
    "plugins": [
      "jsdoc",
    ],
  },
  {
    "files": [
      "**/*.?([cm])[jt]s?(x)",
    ],
    "name": "vinicunca/jsdoc/rules",
    "rules": [
      "jsdoc/check-access",
      "jsdoc/check-alignment",
      "jsdoc/check-param-names",
      "jsdoc/check-property-names",
      "jsdoc/check-types",
      "jsdoc/empty-tags",
      "jsdoc/implements-on-classes",
      "jsdoc/multiline-blocks",
      "jsdoc/no-defaults",
      "jsdoc/no-multi-asterisks",
      "jsdoc/no-types",
      "jsdoc/require-param-name",
      "jsdoc/require-property",
      "jsdoc/require-property-description",
      "jsdoc/require-property-name",
      "jsdoc/require-returns-check",
      "jsdoc/require-returns-description",
      "jsdoc/require-yields-check",
      "jsdoc/valid-types",
    ],
  },
  {
    "name": "vinicunca/imports/rules",
    "plugins": [
      "antfu",
      "import",
    ],
    "rules": [
      "antfu/import-dedupe",
      "antfu/no-import-dist",
      "antfu/no-import-node-modules-by-path",
      "import/consistent-type-specifier-style",
      "import/first",
      "import/no-duplicates",
      "import/no-mutable-exports",
      "import/no-named-default",
      "import/newline-after-import",
    ],
  },
  {
    "name": "vinicunca/unicorn/rules",
    "plugins": [
      "unicorn",
    ],
    "rules": [
      "unicorn/consistent-empty-array-spread",
      "unicorn/error-message",
      "unicorn/escape-case",
      "unicorn/no-instanceof-builtins",
      "unicorn/no-new-array",
      "unicorn/no-new-buffer",
      "unicorn/number-literal-case",
      "unicorn/prefer-dom-node-text-content",
      "unicorn/prefer-includes",
      "unicorn/prefer-node-protocol",
      "unicorn/prefer-number-properties",
      "unicorn/prefer-string-starts-ends-with",
      "unicorn/prefer-type-error",
      "unicorn/throw-new-error",
    ],
  },
  {
    "files": [
      "**/*.?([cm])jsx",
      "**/*.?([cm])tsx",
    ],
    "languageOptions": {
      "parserOptions": {
        "ecmaFeatures": {
          "jsx": true,
        },
      },
    },
    "name": "antfu/jsx/setup",
    "plugins": [],
    "rules": [],
  },
  {
    "name": "vinicunca/typescript/setup",
    "plugins": [
      "antfu",
      "ts",
    ],
  },
  {
    "files": [
      "**/*.?([cm])ts",
      "**/*.?([cm])tsx",
      "**/*.vue",
    ],
    "languageOptions": {
      "parser": "typescript-eslint/parser",
      "parserOptions": {
        "extraFileExtensions": [
          ".vue",
        ],
        "sourceType": "module",
      },
    },
    "name": "vinicunca/typescript/parser",
  },
  {
    "files": [
      "**/*.?([cm])ts",
      "**/*.?([cm])tsx",
      "**/*.vue",
    ],
    "name": "vinicunca/typescript/rules",
    "rules": [
      "- constructor-super",
      "- getter-return",
      "- no-class-assign",
      "- no-const-assign",
      "- no-dupe-args",
      "- no-dupe-class-members",
      "- no-dupe-keys",
      "- no-func-assign",
      "- no-import-assign",
      "- no-new-native-nonconstructor",
      "- no-new-symbol",
      "- no-obj-calls",
      "- no-redeclare",
      "- no-setter-return",
      "- no-this-before-super",
      "- no-undef",
      "- no-unreachable",
      "- no-unsafe-negation",
      "no-var",
      "- no-with",
      "prefer-const",
      "prefer-rest-params",
      "prefer-spread",
      "ts/ban-ts-comment",
      "- no-array-constructor",
      "ts/no-array-constructor",
      "ts/no-duplicate-enum-values",
      "ts/no-dynamic-delete",
      "ts/no-empty-object-type",
      "- ts/no-explicit-any",
      "ts/no-extra-non-null-assertion",
      "- ts/no-extraneous-class",
      "- ts/no-invalid-void-type",
      "ts/no-misused-new",
      "ts/no-namespace",
      "ts/no-non-null-asserted-nullish-coalescing",
      "ts/no-non-null-asserted-optional-chain",
      "- ts/no-non-null-assertion",
      "ts/no-require-imports",
      "ts/no-this-alias",
      "ts/no-unnecessary-type-constraint",
      "ts/no-unsafe-declaration-merging",
      "ts/no-unsafe-function-type",
      "- no-unused-expressions",
      "ts/no-unused-expressions",
      "- no-unused-vars",
      "ts/no-unused-vars",
      "- no-useless-constructor",
      "ts/no-useless-constructor",
      "ts/no-wrapper-object-types",
      "ts/prefer-as-const",
      "ts/prefer-literal-enum-member",
      "ts/prefer-namespace-keyword",
      "- ts/triple-slash-reference",
      "ts/unified-signatures",
      "- no-use-before-define",
      "ts/array-type",
      "ts/consistent-type-definitions",
      "ts/consistent-type-imports",
      "- ts/explicit-member-accessibility",
      "- ts/explicit-module-boundary-types",
      "ts/method-signature-style",
      "- ts/naming-convention",
      "ts/no-dupe-class-members",
      "- ts/no-empty-function",
      "ts/no-import-type-side-effects",
      "ts/no-invalid-this",
      "ts/no-redeclare",
      "ts/no-use-before-define",
      "- ts/parameter-properties",
    ],
  },
  {
    "name": "vinicunca/stylistic/rules",
    "plugins": [
      "antfu",
      "style",
    ],
    "rules": [
      "style/array-bracket-spacing",
      "style/arrow-parens",
      "style/arrow-spacing",
      "style/block-spacing",
      "style/brace-style",
      "style/comma-dangle",
      "style/comma-spacing",
      "style/comma-style",
      "style/computed-property-spacing",
      "style/dot-location",
      "style/eol-last",
      "style/generator-star-spacing",
      "style/indent",
      "style/indent-binary-ops",
      "style/key-spacing",
      "style/keyword-spacing",
      "style/lines-between-class-members",
      "style/max-statements-per-line",
      "style/member-delimiter-style",
      "style/multiline-ternary",
      "style/new-parens",
      "style/no-extra-parens",
      "style/no-floating-decimal",
      "style/no-mixed-operators",
      "style/no-mixed-spaces-and-tabs",
      "style/no-multi-spaces",
      "style/no-multiple-empty-lines",
      "style/no-tabs",
      "style/no-trailing-spaces",
      "style/no-whitespace-before-property",
      "style/object-curly-spacing",
      "style/operator-linebreak",
      "style/padded-blocks",
      "style/quote-props",
      "style/quotes",
      "style/rest-spread-spacing",
      "style/semi",
      "style/semi-spacing",
      "style/space-before-blocks",
      "style/space-before-function-paren",
      "style/space-in-parens",
      "style/space-infix-ops",
      "style/space-unary-ops",
      "style/spaced-comment",
      "style/template-curly-spacing",
      "style/template-tag-spacing",
      "style/type-annotation-spacing",
      "style/type-generic-spacing",
      "style/type-named-tuple-spacing",
      "style/wrap-iife",
      "style/yield-star-spacing",
      "style/jsx-closing-bracket-location",
      "style/jsx-closing-tag-location",
      "style/jsx-curly-brace-presence",
      "style/jsx-curly-newline",
      "style/jsx-curly-spacing",
      "style/jsx-equals-spacing",
      "style/jsx-first-prop-new-line",
      "style/jsx-function-call-newline",
      "style/jsx-indent-props",
      "style/jsx-max-props-per-line",
      "style/jsx-one-expression-per-line",
      "style/jsx-quotes",
      "style/jsx-tag-spacing",
      "style/jsx-wrap-multilines",
      "antfu/consistent-list-newline",
      "antfu/consistent-chaining",
      "antfu/top-level-function",
      "curly",
      "style/array-bracket-newline",
      "style/array-element-newline",
      "style/function-call-spacing",
      "style/object-curly-newline",
      "style/object-property-newline",
    ],
  },
  {
    "name": "vinicunca/regexp/rules",
    "plugins": [
      "regexp",
    ],
    "rules": [
      "no-control-regex",
      "no-misleading-character-class",
      "no-regex-spaces",
      "prefer-regex-literals",
      "- no-invalid-regexp",
      "- no-useless-backreference",
      "- no-empty-character-class",
      "regexp/confusing-quantifier",
      "regexp/control-character-escape",
      "regexp/match-any",
      "regexp/negation",
      "regexp/no-contradiction-with-assertion",
      "regexp/no-dupe-characters-character-class",
      "regexp/no-dupe-disjunctions",
      "regexp/no-empty-alternative",
      "regexp/no-empty-capturing-group",
      "regexp/no-empty-character-class",
      "regexp/no-empty-group",
      "regexp/no-empty-lookarounds-assertion",
      "regexp/no-empty-string-literal",
      "regexp/no-escape-backspace",
      "regexp/no-extra-lookaround-assertions",
      "regexp/no-invalid-regexp",
      "regexp/no-invisible-character",
      "regexp/no-lazy-ends",
      "regexp/no-legacy-features",
      "regexp/no-misleading-capturing-group",
      "regexp/no-misleading-unicode-character",
      "regexp/no-missing-g-flag",
      "regexp/no-non-standard-flag",
      "regexp/no-obscure-range",
      "regexp/no-optional-assertion",
      "regexp/no-potentially-useless-backreference",
      "regexp/no-super-linear-backtracking",
      "regexp/no-trivially-nested-assertion",
      "regexp/no-trivially-nested-quantifier",
      "regexp/no-unused-capturing-group",
      "regexp/no-useless-assertions",
      "regexp/no-useless-backreference",
      "regexp/no-useless-character-class",
      "regexp/no-useless-dollar-replacements",
      "regexp/no-useless-escape",
      "regexp/no-useless-flag",
      "regexp/no-useless-lazy",
      "regexp/no-useless-non-capturing-group",
      "regexp/no-useless-quantifier",
      "regexp/no-useless-range",
      "regexp/no-useless-set-operand",
      "regexp/no-useless-string-literal",
      "regexp/no-useless-two-nums-quantifier",
      "regexp/no-zero-quantifier",
      "regexp/optimal-lookaround-quantifier",
      "regexp/optimal-quantifier-concatenation",
      "regexp/prefer-character-class",
      "regexp/prefer-d",
      "regexp/prefer-plus-quantifier",
      "regexp/prefer-predefined-assertion",
      "regexp/prefer-question-quantifier",
      "regexp/prefer-range",
      "regexp/prefer-set-operation",
      "regexp/prefer-star-quantifier",
      "regexp/prefer-unicode-codepoint-escapes",
      "regexp/prefer-w",
      "regexp/simplify-set-operations",
      "regexp/sort-flags",
      "regexp/strict",
      "regexp/use-ignore-case",
    ],
  },
  {
    "name": "vinicunca/test/setup",
    "plugins": [
      "test",
    ],
  },
  {
    "files": [
      "**/__tests__/**/*.?([cm])[jt]s?(x)",
      "**/*.spec.?([cm])[jt]s?(x)",
      "**/*.test.?([cm])[jt]s?(x)",
      "**/*.bench.?([cm])[jt]s?(x)",
      "**/*.benchmark.?([cm])[jt]s?(x)",
    ],
    "name": "vinicunca/test/rules",
    "rules": [
      "- sonar/no-duplicate-string",
      "test/consistent-test-it",
      "test/no-identical-title",
      "test/no-import-node-test",
      "test/no-only-tests",
      "test/prefer-hooks-in-order",
      "test/prefer-lowercase-title",
      "- antfu/no-top-level-await",
      "- no-unused-expressions",
      "- node/prefer-global/process",
      "- ts/explicit-function-return-type",
    ],
  },
  {
    "languageOptions": {},
    "name": "vinicunca/vue/setup",
    "plugins": [
      "vue",
    ],
  },
  {
    "files": [
      "**/*.vue",
    ],
    "languageOptions": {
      "parser": "vue-eslint-parser",
      "parserOptions": {
        "ecmaFeatures": {
          "jsx": true,
        },
        "extraFileExtensions": [
          ".vue",
        ],
        "sourceType": "module",
      },
    },
    "name": "vinicunca/vue/rules",
    "processor": "merged-processor:eslint-plugin-vue+eslint-processor-vue-blocks",
    "rules": [
      "vue/comment-directive",
      "vue/jsx-uses-vars",
      "- vue/multi-word-component-names",
      "vue/no-arrow-functions-in-watch",
      "vue/no-async-in-computed-properties",
      "vue/no-child-content",
      "vue/no-computed-properties-in-data",
      "vue/no-deprecated-data-object-declaration",
      "vue/no-deprecated-delete-set",
      "vue/no-deprecated-destroyed-lifecycle",
      "vue/no-deprecated-dollar-listeners-api",
      "vue/no-deprecated-dollar-scopedslots-api",
      "vue/no-deprecated-events-api",
      "vue/no-deprecated-filter",
      "vue/no-deprecated-functional-template",
      "vue/no-deprecated-html-element-is",
      "vue/no-deprecated-inline-template",
      "vue/no-deprecated-model-definition",
      "vue/no-deprecated-props-default-this",
      "vue/no-deprecated-router-link-tag-prop",
      "vue/no-deprecated-scope-attribute",
      "vue/no-deprecated-slot-attribute",
      "vue/no-deprecated-slot-scope-attribute",
      "vue/no-deprecated-v-bind-sync",
      "vue/no-deprecated-v-is",
      "vue/no-deprecated-v-on-native-modifier",
      "vue/no-deprecated-v-on-number-modifiers",
      "vue/no-deprecated-vue-config-keycodes",
      "- vue/no-dupe-keys",
      "vue/no-dupe-v-else-if",
      "vue/no-duplicate-attributes",
      "vue/no-export-in-script-setup",
      "vue/no-expose-after-await",
      "vue/no-lifecycle-after-await",
      "vue/no-mutating-props",
      "vue/no-parsing-error",
      "vue/no-ref-as-operand",
      "vue/no-reserved-component-names",
      "vue/no-reserved-keys",
      "vue/no-reserved-props",
      "vue/no-shared-component-data",
      "vue/no-side-effects-in-computed-properties",
      "vue/no-template-key",
      "vue/no-textarea-mustache",
      "vue/no-unused-components",
      "vue/no-unused-vars",
      "vue/no-use-computed-property-like-method",
      "vue/no-use-v-if-with-v-for",
      "vue/no-useless-template-attributes",
      "vue/no-v-for-template-key-on-child",
      "- vue/no-v-text-v-html-on-component",
      "vue/no-watch-after-await",
      "- vue/prefer-import-from-vue",
      "vue/require-component-is",
      "vue/require-prop-type-constructor",
      "vue/require-render-return",
      "vue/require-slots-as-functions",
      "vue/require-toggle-inside-transition",
      "vue/require-v-for-key",
      "vue/require-valid-default-prop",
      "vue/return-in-computed-property",
      "vue/return-in-emits-validator",
      "vue/use-v-on-exact",
      "vue/valid-attribute-name",
      "vue/valid-define-emits",
      "vue/valid-define-options",
      "vue/valid-define-props",
      "vue/valid-next-tick",
      "vue/valid-template-root",
      "vue/valid-v-bind",
      "vue/valid-v-cloak",
      "vue/valid-v-else-if",
      "vue/valid-v-else",
      "vue/valid-v-for",
      "vue/valid-v-html",
      "vue/valid-v-if",
      "vue/valid-v-is",
      "vue/valid-v-memo",
      "vue/valid-v-model",
      "vue/valid-v-on",
      "vue/valid-v-once",
      "vue/valid-v-pre",
      "vue/valid-v-show",
      "vue/valid-v-slot",
      "vue/valid-v-text",
      "vue/attribute-hyphenation",
      "vue/component-definition-name-casing",
      "vue/first-attribute-linebreak",
      "vue/html-closing-bracket-newline",
      "vue/html-closing-bracket-spacing",
      "vue/html-end-tags",
      "vue/html-indent",
      "vue/html-quotes",
      "vue/html-self-closing",
      "vue/max-attributes-per-line",
      "vue/multiline-html-element-content-newline",
      "vue/mustache-interpolation-spacing",
      "vue/no-multi-spaces",
      "vue/no-spaces-around-equal-signs-in-attribute",
      "vue/no-template-shadow",
      "vue/one-component-per-file",
      "vue/prop-name-casing",
      "- vue/require-default-prop",
      "vue/require-explicit-emits",
      "- vue/require-prop-types",
      "vue/singleline-html-element-content-newline",
      "vue/v-bind-style",
      "vue/v-on-event-hyphenation",
      "vue/v-on-style",
      "vue/v-slot-style",
      "vue/attributes-order",
      "vue/block-order",
      "vue/no-lone-template",
      "vue/no-multiple-slot-args",
      "vue/no-required-prop-with-default",
      "- vue/no-v-html",
      "vue/order-in-components",
      "vue/this-in-template",
      "- antfu/no-top-level-await",
      "- node/prefer-global/process",
      "- ts/explicit-function-return-type",
      "vue/component-name-in-template-casing",
      "vue/component-options-name-casing",
      "- vue/component-tags-order",
      "vue/custom-event-name-casing",
      "vue/define-macros-order",
      "vue/dot-location",
      "vue/dot-notation",
      "vue/eqeqeq",
      "vue/no-constant-condition",
      "vue/no-empty-pattern",
      "vue/no-irregular-whitespace",
      "vue/no-loss-of-precision",
      "vue/no-restricted-syntax",
      "vue/no-restricted-v-bind",
      "- vue/no-setup-props-reactivity-loss",
      "vue/no-sparse-arrays",
      "vue/no-unused-refs",
      "vue/no-useless-v-bind",
      "vue/object-shorthand",
      "vue/prefer-separate-static-class",
      "vue/prefer-template",
      "vue/space-infix-ops",
      "vue/space-unary-ops",
      "vue/array-bracket-spacing",
      "vue/arrow-spacing",
      "vue/block-spacing",
      "vue/block-tag-newline",
      "vue/brace-style",
      "vue/comma-dangle",
      "vue/comma-spacing",
      "vue/comma-style",
      "vue/html-comment-content-spacing",
      "vue/key-spacing",
      "vue/keyword-spacing",
      "vue/object-curly-newline",
      "vue/object-curly-spacing",
      "vue/object-property-newline",
      "vue/operator-linebreak",
      "vue/padding-line-between-blocks",
      "vue/quote-props",
      "vue/space-in-parens",
      "vue/template-curly-spacing",
    ],
  },
  {
    "name": "vinicunca/jsonc/setup",
    "plugins": [
      "jsonc",
    ],
  },
  {
    "files": [
      "**/*.json",
      "**/*.json5",
      "**/*.jsonc",
    ],
    "language": "jsonc/x",
    "name": "vinicunca/jsonc/rules",
    "rules": [
      "jsonc/no-bigint-literals",
      "jsonc/no-binary-expression",
      "jsonc/no-binary-numeric-literals",
      "jsonc/no-dupe-keys",
      "jsonc/no-escape-sequence-in-identifier",
      "jsonc/no-floating-decimal",
      "jsonc/no-hexadecimal-numeric-literals",
      "jsonc/no-infinity",
      "jsonc/no-multi-str",
      "jsonc/no-nan",
      "jsonc/no-number-props",
      "jsonc/no-numeric-separators",
      "jsonc/no-octal",
      "jsonc/no-octal-escape",
      "jsonc/no-octal-numeric-literals",
      "jsonc/no-parenthesized",
      "jsonc/no-plus-sign",
      "jsonc/no-regexp-literals",
      "jsonc/no-sparse-arrays",
      "jsonc/no-template-literals",
      "jsonc/no-undefined-value",
      "jsonc/no-unicode-codepoint-escapes",
      "jsonc/no-useless-escape",
      "jsonc/space-unary-ops",
      "jsonc/valid-json-number",
      "jsonc/vue-custom-block/no-parsing-error",
      "jsonc/array-bracket-spacing",
      "jsonc/comma-dangle",
      "jsonc/comma-style",
      "jsonc/indent",
      "jsonc/key-spacing",
      "jsonc/object-curly-newline",
      "jsonc/object-curly-spacing",
      "jsonc/object-property-newline",
      "jsonc/quote-props",
      "jsonc/quotes",
    ],
  },
  {
    "files": [
      "**/package.json",
    ],
    "name": "vinicunca/sort/package-json",
    "rules": [
      "jsonc/sort-array-values",
      "jsonc/sort-keys",
    ],
  },
  {
    "files": [
      "**/[jt]sconfig.json",
      "**/[jt]sconfig.*.json",
    ],
    "name": "vinicunca/sort/tsconfig",
    "rules": [
      "jsonc/sort-keys",
    ],
  },
  {
    "files": [
      "package.json",
      "**/package.json",
    ],
    "language": "jsonc/x",
    "name": "vinicunca/pnpm/package-json",
    "plugins": [
      "pnpm",
    ],
    "rules": [
      "pnpm/json-enforce-catalog",
      "pnpm/json-prefer-workspace-settings",
      "pnpm/json-valid-catalog",
    ],
  },
  {
    "files": [
      "pnpm-workspace.yaml",
    ],
    "languageOptions": {
      "parser": "yaml-eslint-parser",
    },
    "name": "vinicunca/pnpm/pnpm-workspace-yaml",
    "plugins": [
      "pnpm",
    ],
    "rules": [
      "pnpm/yaml-enforce-settings",
      "pnpm/yaml-no-duplicate-catalog-item",
      "pnpm/yaml-no-unused-catalog-item",
    ],
  },
  {
    "files": [
      "pnpm-workspace.yaml",
    ],
    "languageOptions": {
      "parser": "yaml-eslint-parser",
    },
    "name": "vinicunca/pnpm/pnpm-workspace-yaml-sort",
    "plugins": [
      "yaml",
    ],
    "rules": [
      "yaml/sort-keys",
    ],
  },
  {
    "name": "vinicunca/yaml/setup",
    "plugins": [
      "yaml",
    ],
  },
  {
    "files": [
      "**/*.y?(a)ml",
    ],
    "languageOptions": {
      "parser": "yaml-eslint-parser",
    },
    "name": "vinicunca/yaml/rules",
    "rules": [
      "- style/spaced-comment",
      "yaml/block-mapping",
      "yaml/block-sequence",
      "yaml/no-empty-key",
      "yaml/no-empty-sequence-entry",
      "yaml/no-irregular-whitespace",
      "yaml/plain-scalar",
      "yaml/vue-custom-block/no-parsing-error",
      "yaml/block-mapping-question-indicator-newline",
      "yaml/block-sequence-hyphen-indicator-newline",
      "yaml/flow-mapping-curly-newline",
      "yaml/flow-mapping-curly-spacing",
      "yaml/flow-sequence-bracket-newline",
      "yaml/flow-sequence-bracket-spacing",
      "yaml/indent",
      "yaml/key-spacing",
      "yaml/no-tab-indent",
      "yaml/quotes",
      "yaml/spaced-comment",
    ],
  },
  {
    "name": "vinicunca/toml/setup",
    "plugins": [
      "toml",
    ],
  },
  {
    "files": [
      "**/*.toml",
    ],
    "languageOptions": {
      "parser": "toml-eslint-parser",
    },
    "name": "vinicunca/toml/rules",
    "rules": [
      "- style/spaced-comment",
      "toml/comma-style",
      "toml/keys-order",
      "toml/no-space-dots",
      "toml/no-unreadable-number-separator",
      "toml/precision-of-fractional-seconds",
      "toml/precision-of-integer",
      "toml/tables-order",
      "toml/vue-custom-block/no-parsing-error",
      "toml/array-bracket-newline",
      "toml/array-bracket-spacing",
      "toml/array-element-newline",
      "toml/indent",
      "toml/inline-table-curly-spacing",
      "toml/key-spacing",
      "toml/padding-line-between-pairs",
      "toml/padding-line-between-tables",
      "toml/quoted-keys",
      "toml/spaced-comment",
      "toml/table-bracket-spacing",
    ],
  },
  {
    "name": "vinicunca/markdown/setup",
    "plugins": [
      "markdown",
    ],
  },
  {
    "files": [
      "**/*.md",
    ],
    "ignores": [
      "**/*.md/*.md",
    ],
    "name": "vinicunca/markdown/processor",
    "processor": "merged-processor:@eslint/markdown/markdown+pass-through",
  },
  {
    "files": [
      "**/*.md",
    ],
    "language": "markdown/gfm",
    "name": "vinicunca/markdown/parser",
  },
  {
    "files": [
      "**/*.md",
    ],
    "name": "vinicunca/markdown/rules",
    "rules": [
      "markdown/fenced-code-language",
      "markdown/heading-increment",
      "markdown/no-duplicate-definitions",
      "markdown/no-empty-definitions",
      "markdown/no-empty-images",
      "markdown/no-empty-links",
      "markdown/no-invalid-label-refs",
      "markdown/no-missing-atx-heading-space",
      "- markdown/no-missing-label-refs",
      "markdown/no-missing-link-fragments",
      "markdown/no-multiple-h1",
      "markdown/no-reference-like-urls",
      "markdown/no-reversed-media-syntax",
      "markdown/no-space-in-emphasis",
      "markdown/no-unused-definitions",
      "markdown/require-alt-text",
      "markdown/table-column-count",
    ],
  },
  {
    "files": [
      "**/*.md",
    ],
    "name": "vinicunca/markdown/disables/markdown",
    "rules": [
      "- command/command",
      "- no-irregular-whitespace",
      "- perfectionist/sort-exports",
      "- perfectionist/sort-imports",
      "- regexp/no-legacy-features",
      "- regexp/no-missing-g-flag",
      "- regexp/no-useless-dollar-replacements",
      "- regexp/no-useless-flag",
      "- style/indent",
    ],
  },
  {
    "files": [
      "**/*.md/**/*.?([cm])[jt]s?(x)",
      "**/*.md/**/*.vue",
    ],
    "languageOptions": {
      "parserOptions": {
        "ecmaFeatures": {
          "impliedStrict": true,
        },
      },
    },
    "name": "vinicunca/markdown/disables",
    "rules": [
      "- no-alert",
      "- no-console",
      "- no-undef",
      "- no-unused-expressions",
      "- no-unused-vars",
      "- node/prefer-global/process",
      "- style/comma-dangle",
      "- style/eol-last",
      "- style/padding-line-between-statements",
      "- ts/consistent-type-imports",
      "- ts/no-namespace",
      "- ts/no-redeclare",
      "- ts/no-require-imports",
      "- ts/no-unused-vars",
      "- ts/no-use-before-define",
      "- unicode-bom",
      "- unused-imports/no-unused-imports",
      "- unused-imports/no-unused-vars",
    ],
  },
  {
    "files": [
      "**/scripts/**/*.?([cm])[jt]s?(x)",
    ],
    "name": "vinicunca/disables/scripts",
    "rules": [
      "- antfu/no-top-level-await",
      "- no-console",
      "- ts/explicit-function-return-type",
    ],
  },
  {
    "files": [
      "**/cli/**/*.?([cm])[jt]s?(x)",
      "**/cli.?([cm])[jt]s?(x)",
    ],
    "name": "vinicunca/disables/cli",
    "rules": [
      "- antfu/no-top-level-await",
      "- no-console",
    ],
  },
  {
    "files": [
      "**/bin/**/*",
      "**/bin.?([cm])[jt]s?(x)",
    ],
    "name": "vinicunca/disables/bin",
    "rules": [
      "- antfu/no-import-dist",
      "- antfu/no-import-node-modules-by-path",
    ],
  },
  {
    "files": [
      "**/*.d.?([cm])ts",
    ],
    "name": "vinicunca/disables/dts",
    "rules": [
      "- eslint-comments/no-unlimited-disable",
      "- no-restricted-syntax",
      "- unused-imports/no-unused-vars",
    ],
  },
  {
    "files": [
      "**/*.js",
      "**/*.cjs",
    ],
    "name": "vinicunca/disables/cjs",
    "rules": [
      "- ts/no-require-imports",
    ],
  },
  {
    "files": [
      "**/*.config.?([cm])[jt]s?(x)",
      "**/*.config.*.?([cm])[jt]s?(x)",
    ],
    "name": "vinicunca/disables/config-files",
    "rules": [
      "- antfu/no-top-level-await",
      "- no-console",
      "- ts/explicit-function-return-type",
    ],
  },
]